
# ~/.config/starship.toml
add_newline = false

[character]
success_symbol = "[➜](bold green) "
error_symbol   = "[➜](bold red) "

[directory]
truncation_length = 3

[git_status]
conflicted = "✖"
staged     = "●"
modified   = "✚"
untracked  = "…"
