[[language]]
name = "rust"
formatter = { command = "rustfmt", args = ["--emit=stdout"] }
language-servers = [ "rust-analyzer" ]
indent = { tab-width = 4, unit = "    " }

[language-server.rust-analyzer]
command = "/home/fard/dev/tools/rust/rustup/toolchains/stable-x86_64-unknown-linux-gnu/bin/rust-analyzer"


[language-server.rust-analyzer.config]
cargo.allFeatures = false
procMacro.enable = true
check.command = "clippy"
inlayHints.bindingModeHints.enable = true
inlayHints.chainingHints.enable = true
inlayHints.closingBraceHints.enable = true
inlayHints.closingBraceHints.minLines = 10
inlayHints.parameterHints.enable = true
inlayHints.typeHints.enable = true
inlayHints.typeHints.hideLessSpecificTypes = true

hover.actions.enable = true
completion.autoimport.enable = true

[[language]]
name = "c"
language-servers = [ "clangd" ]
formatter = { command = "clang-format" }
indent = { tab-width = 4, unit = "    " }

[language-server.clangd]
command = "clangd"
